pudo/dataset

dataset/persistence/table.py

Hi, the database lock wasn't being released when dropping a table. This caused dataset to hang in some cases.

release lock in table.drop()

---

dataset/freeze/format/fjson.py
test/test_freeze.py

The `wrap` parameter was not used at all by the JSON formatter.

When wrap is False, don't wrap JSON result

---

dataset/persistence/database.py

https://docs.python.org/2/library/threading.html#rlock-objects
```
threading.RLock()
A factory function that returns a new reentrant lock object. A reentrant lock must be released by the thread that acquired it. Once a thread has acquired a reentrant lock, the same thread may acquire it again without blocking; the thread must release it once for each time it has acquired it.
```
In dataset, it will hold all the release operations util transaction commit/rollback, but it `only call the release() once`.
A sample code to reproduce the problem of reentrant lock.
```
import threading
import time
lock = threading.RLock()
lock.acquire()
lock.acquire()
lock.release() # It still holds the lock!!!
def test():
print 'start'
lock.acquire()
print 'end'
lock.release()
t = threading.Thread(target=test) …
```

Release all the locks acquired by transaction on commit/rollback

---

dataset/persistence/table.py

This request is based on issue #133. In summary, this request is to prevent unintentional schema change when using 'insert' or 'update' with default 'ensure=True' setting.
Added 'ensure_session' global variable as a default value for 'ensure' parameter.
I haven't used Python for a long time and I can't test this code for now. I'm sorry for my irresponsibility, but here is a rough idea as a solution.

'ensure_session' session flag as a default value for 'ensure' parameter

---

dataset/persistence/table.py

This is a simple return_ hook to return the selectable instead of the result from table.find.
This is helpful if you want to load the data using sqlalchemy, or something that supports sqlalchemy (such as pandas).
Example:
```
import dataset
import pandas as pd
db = dataset.connect('sqlite:///mydatabase.db')
table=db['user']
table.delete() #clear the table a fresh dev env
table.insert(dict(name='John Doe', age=46, country='China'))
table.insert(dict(name='John Doe', age=19, country='USA'))
table.insert(dict(name='Jane Doe', age=37, country='France', gender='female'))
print(pd.read_sql("user",db.engine))
#0   1   China   46  John Doe    None
#1   2     USA   19  John Doe    None
#2   3  France   37  Jane Doe  female
q=table.find(name="John Doe",return_query=True) …
```

Simple change in table.py to return query from find

---

dataset/freeze/format/fjson.py

Hi,
This fix is needed to handle Decimal() type. If not, a 'null' value is returned. The value I'm working with:
Please find below the behavior I noticed:
**Before json.dumps()**
{'count': 1, 'meta': {}, 'results': [OrderedDict([(u'LAT', Decimal('14.8263245676')), (u'LNG', Decimal('-89.4853961532'))])]}
**After json.dumps()**
{"count": 1, "meta": {}, "results": [{"LAT": null, "LNG": null}]}
So converting Decimal() class object into String() makes it work.
Cheers,

handle Decimal class as a string to avoid "null" as returned value

---

dataset/freeze/format/fjson.py

Hi,
Sorry for the mistake, previous pull request #181 didn't include the Decimal module for handling correctly Decimal() objects.
As discussion is on-going about #181, you may prefer to revert modifications.

import decimal module

---

dataset/persistence/table.py

if don't pass in schema here, it will be None by default.
Fix it to be aware of schema like Table.create_column.

bug fix, make Table.drop_column be aware of table schema

---

dataset/persistence/table.py

Thank you for this insanely useful library. It's a total delight to use. This PR explicitly passes the `unique` keyword to `sqlalchemy.schema.Index`; alternatively, I could take a broader/less-specific approach of having `Table.create_index` accepting `**kw` and passing that to `sqlalchemy.schema.Index`.

Let users pass `unique` boolean to .create_index

---

dataset/freeze/format/fjson.py

To avoid commits like [this one](https://github.com/paulfurley/experimental-liverpool-planning-data/commit/f0599f87bcd0211b2cff977d008119b6aa267bea) on Python 3

Order JSON freeze fields deterministically

---

dataset/persistence/util.py

This is a simple change to allow Date column type (i.e. a raw date without a time) to be guessed from a Python datetime.date type.

Allow Date column type (in addition to existing DateTime type)

---

dataset/persistence/table.py
test/test_persistence.py

This adds a method to create a column by giving an example of the data it will contain rather than by specifying its SQLAlchemy type.  This extends the range of operations that can be performed without reading the SQLAlchemy docs.

add Table.create_column_by_example method

---

dataset/table.py

I was running into the error:
`sqlalchemy.exc.ArgumentError: Trying to redefine primary-key column 'my_key' as a non-primary-key column on table 'my_table'
`
When creating a new table with non-default primary key, this change checks if a column is a primary key column before attempting to add again as non-primary key column.

Check if primary column on first _sync_table call

---

docs/api.rst
docs/requirements.txt

This re-adds the generated documentation for the `freeze` function. While I considered removing it since it's a different repo, I think it makes sense to keep it considering there's no docs page setup for the datafreeze repo. View the associated generated [readthedocs here](http://dataset-fork-matthew.readthedocs.io/en/bugfix-data-export-docs/api.html#data-export).

Fix Export Data documentation

---

docs/_themes/kr/sidebarlogo.html

Sidebar link no longer relevant after project split of datafreeze.

Remove link to old documentation

---

dataset/table.py

Thanks again for making this wonderful library.
I just stumbled for a while trying to figure out what's valid for `create_column(..., type)`, since they didn't seem to map exactly onto SQLAlchemy names.
Update the docs to point to the `Type` class which holds that mapping.

In `create_column` docs, signpost the Types class

---

dataset/table.py

... rather than `[]`
If a table exists, you can treat the output of `find` as an iterator,
specifically you can call `next(find(...))`:
```
>>> db = dataset.connect('sqlite:///:memory1:')
>>> table = db['table_which_exists']
>>> table.insert({'foo': 'x'})
>>> next(table.find(foo='x'))  # no problem
```
But if the table hasn't been created yet, `find(...)` returns an empty list,
which you can't call `next()` on:
```
>>> db = dataset.connect('sqlite:///:memory2:')
>>> table = db_no_table['table_which_doesnt_exis']
>>> next(table.find(foo='x'))
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: 'list' object is not an iterator
```
^^^ rather than a `TypeError`, I'd expect to get a `StopIteration`
exception.

find(): if table doesn't exist, return an iterator

---

dataset/util.py

doing isinstance(obj, Sequence) makes calls with keys of dict impossible
Example:
```
d = {'a':'a', 'b':'b'}
table.upsert(values, d.keys())
```
`d.keys()` is of type `dict_keys(['a', 'b'])` and is not of instance Sequence, but Iterable, therefore `ensure_tuple(dict_keys(['a', 'b']))` returns (dict_keys(['a', 'b']),)
which leads to invalid iteration.

Update util.py - fix ensure_tuple instance check

---

setup.py

normality package was unused and caused problems when installing, see #274,problems were caused by the pyicu dependency. Normality was needed before splitting dataset and datafreeze in different packages, now it is no longer needed. Please release a new version soon so dataset can be installed on python docker alpine image easily.

removed unused package

---

docs/api.rst

Some methods are missing in the api doc.
To avoid this the [sphinx-automodapi](https://github.com/astropy/sphinx-automodapi/) is great, it generates automatically the list of methods and attributes.

Add missing methods in Table api doc

---

dataset/table.py
test/test_dataset.py

Hi!
I noticed an interesting bug with `Table.upsert`: the example from the [documentation](https://dataset.readthedocs.io/en/latest/api.html?highlight=primary%20key#dataset.Table.upsert) does not work.
The checks that should prevent double creation of index column are not quite working. If `self._primary_id` is set to `None`, then the index column with name `id` is created, yet later we try to create it again: https://github.com/pudo/dataset/blob/master/dataset/table.py#L246. This causes following exception (Python 3.6.7, SQLAlchemy 1.3.0b3):
```(venv) $ python fail.py 
Traceback (most recent call last):
File "fail.py", line 7, in <module>
table.upsert(data, ['id'])
File "/.../dataset/dataset/table.py", line 176, in upsert
row = self._sync_columns(row, ensure, types=types)
File …
```

Fix bug when UPSERTing a column named 'id'

---

dataset/table.py
dataset/util.py
test/test_dataset.py

This is my first PR - I hope you will accept it! I do understand, however, that it may require modification.
The project I am working on has dataset transactions which could be simplified and sped up by upsert_many, so I decided to attempt implementing it. Whilst doing so, I realised I also had to also implement update_many. After doing so, I started tinkering with the insert_many code and saw that _sync_columns was run on every row, which slows it down to around half-speed. By checking before inserting only, all of the non-existing columns are created and then no checks are required for the rest of the process.
The implementation of update_many is also very fast with 1,000,000 rows (with only one integer field) taking (9.12s) to update with a random integer, 28x faster than updates in a …

Implement update_many, upsert_many and refactor for a 2x speed-up of insert_many

---

dataset/types.py
test/test_dataset.py

Currently when autocreating a table from sample data, the `guess` method assigns all integers as the Integer type, regardless of its size. This causes problems when autocreating a table with integers larger than 2147483647 or less than -2147483648, as these are beyond the signed range of the Integer type. 
I've added a check to determine if the sample integer is beyond the signed range of the basic Integer type. If that is the case, instead of creating a column with the Integer type it will create a column with the BigInteger type. This will solve the bug where a table is autocreated and then the first insert immediately errors because the integer being inserted is out of range.
This is an error I've gotten before (see below). This PR will solve that error. 
`sqlalchemy.exc.DataError: …

Add support for BigInteger

---

dataset/table.py

_columns_keys() sets _columns to {}, but _sync_table() empties _columns
when table is empty.
This fixes #312

Fix race condition when getting column keys of new table

---

dataset/chunked.py
test/test_dataset.py

This commit adds an optional `callback` argument to the `ChunkedInsert`
object. This callback is a callable object which gets called before the
chunked insert happens. This is useful for clearing any local caches
that may be in place to deal with the eventual consistency resulting
from the delayed nature of the chunked inserts.
For example,
```
cache = set()
chunked_table = ChunkedInsert(table, callback=lambda queue: cache.clear())
while True:
data = get_data_id()
key = data['key']
if key in cache or table.find_one(key=key)
continue
cache.add(key)
chunked_table.insert(data)
```

Add optional callback to ChunkedInsert

---

dataset/chunked.py
test/test_dataset.py

Depends on #314 
The ChunkedInsert object is great for speeding up inserts. This commit does the same for updates. It chunks up updates then sends them to the table's `update_many` in bundles that contain updates to the same fields.
In doing this the ChunkedInsert and new ChunkedUpdate were refactored to inherit from a common `_Chunker` object that does most of the chunking logic. This should also make it simple to add a ChunkedUpsert object.

Added ChunkedUpdate to leverage `update_many`

---

dataset/__init__.py

I removed `freeze` from `__all__` listing.
It likely left remained when splitted into datafreeze package.

Removed freeze from __all__ listing

---

dataset/__init__.py
dataset/database.py

Since 2010, SQLite has supported WAL (Write Ahead Log) mode that supports multi-threaded writes. Without this mode enabled, SQLite throws errors when there are concurrent writes to a database and generally has poorer concurrent performance.  
More background here:
http://www.sqlite.org/wal.html
In this PR, I enabled WAL for non-in-memory SQLite databases. 
See also:
https://github.com/pudo/dataset/issues/239

If the database is SQLite, enable WAL

---

dataset/table.py

Solved #374.
This PR may change the before behavior when users use 'update_many' to update primary key.

Remove all keys from values

---

dataset/__init__.py
dataset/database.py

SQLite has many PRAGMA statements that can help increase performance, but almost all of them require using pramas:
- disable synchronous commits: `PRAGMA synchronous = OFF`
- journal in-memory instead of on-disk:`PRAGMA journal_mode = MEMORY`
- use mmap: `pragma mmap_size = <bytes>;`
- increase page size: `pragma page_size = <bytes>;`
- WAL (already available in dataset): `pragma journal_mode = WAL;`
There are many other pragmas that allow further tuning of SQLite. 
However, there is no easy way right now to pass in these PRAGMAs when SQLite is opened. With this PR, we re-use the functionality of passing in pragmas on database creation (which we currently use for WAL), but extend this to support all PRAGMAs.
sources:
https://stackoverflow.com/questions/1711631/improve-insert-per-second-per …

Allow passing in arbitrary sqlite pragmas

---

dataset/database.py

removed redundant <code>`</code>.
before:
(i.e. <code>SELECT * FROM tbl WHERE a = ?`</code>)
after:
(i.e. <code>SELECT * FROM tbl WHERE a = ?</code>)

docs: fix typo for `Database.query()`

---

dataset/table.py
docs/queries.rst
docs/quickstart.rst

There are small typos in:
- dataset/table.py
- docs/queries.rst
- docs/quickstart.rst
Fixes:
- Should read `significant` rather than `signficant`.
- Should read `parameterisation` rather than `paramterisation`.
- Should read `explicitly` rather than `explicetly`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos
